### ISSUE TITLE
BUILT_EXECUTABLE path in Run.sh script incorrect for M1 Mac

### ISSUE THREAD

**Issue by sebj** [Brett-Best/WKPreferencesExperimentalFeaturesExtractor#1]
I think [the path in the `BUILT_EXECUTABLE` variable of the Run.sh script](https://github.com/Brett-Best/WKPreferencesExperimentalFeaturesExtractor/blob/main/Scripts/run.sh#L8) is incorrect on M1 Macs.

It's currently set to `.build/x86_64-apple-macosx/release/WKPreferencesExperimentalFeaturesExtractor`, but on my machine the correct path is `.build/arm64-apple-macosx/release/WKPreferencesExperimentalFeaturesExtractor` instead

**Comment by Brett-Best** [comment]
Yeah I wasn't sure how to pass the environment variables along with swift run. Also wasn't expecting anyone would discover this repo lol

**Comment by Brett-Best** [comment]
@sebj I updated it anyhow, I haven’t tested it though... edited it on mobile hah

**Comment by sebj** [comment]
@Brett-Best 
> Also wasn't expecting anyone would discover this repo lol

😅 Saw your post in the iOS dev Slack, thought I'd take a look!

Now getting `./Scripts/run.sh:8: command not found: -m` though, I'm afraid

**Comment by Brett-Best** [comment]
@sebj I just did a push, should be much more robust now — could you test?

**Comment by Brett-Best** [comment]
> 😅 Saw your post in the iOS dev Slack, thought I'd take a look!

Forgot I posted it 🤣

**Comment by sebj** [comment]
Works perfectly now, thanks!
